networks:
 expense: {}
volumes:
  mysql:
services:
  #docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  mysql: 
    image: mysql:1.0.0
    networks:
    - expense
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  backend:
    image: backend:1.0.0
    networks: 
    - expense
    container_name: backend
    dependson:
    - mysql
  frontend:
    image: frontend:1.0.0
    networks:
    - expense
    container_name: frontend
    dependson:
    - backend
    ports:
    - 80:80